package main

var currentUser = User{
	ID:     "me",
	Name:   "Me",
	Avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBQpbQel9oNKt2XyTxpX44jsBlk2knXI5Cc72a-eHNJf9Sl8OCqHOvfH_dT7eTzDYCKG1OOVx9jVomNf0tOmyN26e80wI7-W3IuVhbiYkt23dw8V4wu4rOiqXGAMQI7vOKFMLpjyiSLzeFbGhSueo_vIKsm1wDHRkRHBRecm1qPzAB_2EQT4TgYszEuXJgD8dE6eZUq-8zcCYpYbOcY5nZ0d2R3ytZu4OJNacUzFmE5HdlWeN2uC56XGi7QkO4ASLE0MI2kLRkHfrc",
	Status: "online",
}

var mockUsers = []User{
	{ID: "u1", Name: "Alex Thompson", Avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCKkuDTlknPZ9zVu10T2BVU1Mkg8bSF67xEr-e0kPZN3xyYMPIYhKsSQZIbXAWcEnPuV-q5JuNqP75mgnzzo6adhVebJFglRX7tsYtuAkNt-iBKA6Wug0UQFd7GfCxUpWTT2dJ5OQkzGL15olsiwxQakgfeN_wG2Aca2yJjvG4myL5ve7nXyTuTX8WekJTM5ZPnkamaL19X_cNkuIo2JzZwjdhjSZcl_egG-XQDVOVJmtOJT1c0l66DnZNjdHOcM7vPfTsZkW_yVPQ", Status: "online"},
	{ID: "u2", Name: "David Chen", Avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAcDAkeKd_OgauMWIlHdnx-AScpLSyGGcMnPrajrzneShk5iCGnl1SfnxTlQzXgnMKKp-hdTE8ILHacIW594dvVC0Azyt6ANx_Z88ygRDxmGwB3ZbOVFLoS08q9vTTrQRTAXsTES20IeYstJdLKBW54R-PQ3tzmIgmQR_ay4ZY9IASKOBGCnpfWiszxzWJTMWd9wKPRAIItJJJNfDoPCfJ0uzU5E3O1hHFSbsJlJgRkRQzYeL9W5Y7FmYLUh25X-1bSkbk8EpqrWDk", Status: "last seen yesterday"},
	{ID: "u3", Name: "Sarah Jenkins", Avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuB3WzGGXuON5bdmZa6KZ5Y0L3WMvtDN3AAQoYAbGHj1H5NvlymI3Q2vdpqdd_bGgOHAmpXtqd2ayDd7JTvMnKkqNOB7Bbm_YjraiYzeRJQJ6F-Gp4ZYew6FW6dkgE6J8yGvpVMNkbKHisADs9W8LOsyZRPqsoQAYlfmkOc6j3Rg79WG-3rg9x72yFSF9EC6es2aUF9zyMbFmajpVJiTgVD5zzgQ23TRfx93WL4_J6rsICEdUq0wMGKUEafip4JLExzV3_190zcz7kI", Status: "last seen 2 hours ago"},
	{ID: "u4", Name: "Maria Rodriguez", Avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuD0odOdWjMhHLpR8RskLpq1kLtf12AqJssSW8hUvkiNhl4S3xYveXeXR4dlRDDLqW5brU3grf1Mjuzvr0x7W3FHhF-OjUpdp2u85T1mZCyF60I1PfpdzsvcxVXq76jchUhQNgOgnmMmrgD0HKBwbYpZIAK3WVdEbAm10pf_INEZiVzF_QBqGzwOrqUGyB7lCZ4OfYcHi2WrDLsUzM-3wFMSUSxJTJ83faaUSLZsrzJeszvHm-xzqFCiIjvphNDXLU5SLA9dReCMfgA", Status: "online"},
	{ID: "u5", Name: "Priya Nair", Avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop", Status: "typing..."},
	{ID: "u6", Name: "Omar Haddad", Avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop", Status: "online"},
	{ID: "u7", Name: "Nina Park", Avatar: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?q=80&w=200&auto=format&fit=crop", Status: "last seen today at 9:02 AM"},
	{ID: "u8", Name: "Leo Martins", Avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=200&auto=format&fit=crop", Status: "online"},
	{ID: "u9", Name: "Jules Bernard", Avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop", Status: "last seen monday"},
	{ID: "u10", Name: "Marta Kowalski", Avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=200&auto=format&fit=crop", Status: "online"},
	{ID: "u11", Name: "Noah Williams", Avatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?q=80&w=200&auto=format&fit=crop", Status: "online"},
	{ID: "u12", Name: "Elena Petrova", Avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop", Status: "last seen today at 8:11 AM"},
}

// --- Mock Chats ---

var mockChats = []Chat{
	{ID: "c1", Participants: []User{currentUser, mockUsers[0]}, LastMessage: &Message{ID: "m1_8", SenderID: "u1", Text: "Did you see the new architectural sketches?", Timestamp: "10:45 AM", Status: "read"}, UnreadCount: 2, IsGroup: false, IsArchived: false, IsStarred: true},
	{ID: "c2", Participants: []User{currentUser, mockUsers[1]}, LastMessage: &Message{ID: "m2_7", SenderID: "me", Text: "The Precision Architect philosophy looks great.", Timestamp: "Yesterday", Status: "read"}, UnreadCount: 0, IsGroup: false, IsArchived: false, IsStarred: true},
	{ID: "c3", Participants: []User{currentUser, mockUsers[0], mockUsers[2], mockUsers[3], mockUsers[5]}, LastMessage: &Message{ID: "m3_9", SenderID: "u4", Text: "Sarah: Send over those final PNGs please!", Timestamp: "Yesterday", Status: "read"}, UnreadCount: 0, IsGroup: true, Name: ptr("Design Sprint 2024"), Avatar: ptr("https://images.unsplash.com/photo-1522071823991-b96767a1c56f?q=80&w=200&auto=format&fit=crop"), IsArchived: false, IsStarred: true, IsCommunity: true},
	{ID: "c4", Participants: []User{currentUser, mockUsers[3]}, LastMessage: &Message{ID: "m4_6", SenderID: "u4", Text: "Call me when you're free.", Timestamp: "Wednesday", Status: "sent"}, UnreadCount: 0, IsGroup: false, IsArchived: false},
	{ID: "c5", Participants: []User{currentUser, mockUsers[2]}, LastMessage: &Message{ID: "m5_5", SenderID: "u3", Text: "The contract has been archived safely.", Timestamp: "Dec 22", Status: "read"}, UnreadCount: 0, IsGroup: false, IsArchived: true},
	{ID: "c6", Participants: []User{currentUser, mockUsers[4]}, LastMessage: &Message{ID: "m6_7", SenderID: "u5", Text: "Typing out the launch copy now. Want first pass in 20?", Timestamp: "9:18 AM", Status: "delivered"}, UnreadCount: 4, IsGroup: false, IsArchived: false, IsStarred: true},
	{ID: "c7", Participants: []User{currentUser, mockUsers[5]}, LastMessage: &Message{ID: "m7_6", SenderID: "me", Text: "Shipping manifests are all reconciled.", Timestamp: "8:07 AM", Status: "read"}, UnreadCount: 0, IsGroup: false, IsArchived: false},
	{ID: "c8", Participants: []User{currentUser, mockUsers[6], mockUsers[8], mockUsers[10]}, LastMessage: &Message{ID: "m8_8", SenderID: "u7", Text: "We should lock the venue by tonight.", Timestamp: "7:55 AM", Status: "read"}, UnreadCount: 7, IsGroup: true, Name: ptr("Offsite Planning"), Avatar: ptr("https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=200&auto=format&fit=crop"), IsArchived: false, IsCommunity: true},
	{ID: "c9", Participants: []User{currentUser, mockUsers[7]}, LastMessage: &Message{ID: "m9_5", SenderID: "u8", Text: "Dropped the raw images in the shared drive.", Timestamp: "Mon", Status: "read"}, UnreadCount: 0, IsGroup: false, IsArchived: false},
	{ID: "c10", Participants: []User{currentUser, mockUsers[8]}, LastMessage: &Message{ID: "m10_5", SenderID: "u9", Text: "Can you review the French copy when you wake up?", Timestamp: "Sun", Status: "delivered"}, UnreadCount: 1, IsGroup: false, IsArchived: false},
	{ID: "c11", Participants: []User{currentUser, mockUsers[9], mockUsers[11], mockUsers[4], mockUsers[6]}, LastMessage: &Message{ID: "m11_9", SenderID: "u10", Text: "Budget sheet updated with the final hotel numbers.", Timestamp: "Sun", Status: "read"}, UnreadCount: 3, IsGroup: true, Name: ptr("Ops Core"), Avatar: ptr("https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=200&auto=format&fit=crop"), IsArchived: false, IsCommunity: true, IsStarred: true},
	{ID: "c12", Participants: []User{currentUser, mockUsers[10]}, LastMessage: &Message{ID: "m12_4", SenderID: "me", Text: "I'll send a cleaner build after lunch.", Timestamp: "Sat", Status: "read"}, UnreadCount: 0, IsGroup: false, IsArchived: false},
	{ID: "c13", Participants: []User{currentUser, mockUsers[11]}, LastMessage: &Message{ID: "m13_6", SenderID: "u12", Text: "Archive this one after finance replies.", Timestamp: "Fri", Status: "read"}, UnreadCount: 0, IsGroup: false, IsArchived: true},
	{ID: "c14", Participants: []User{currentUser, mockUsers[1], mockUsers[5], mockUsers[9]}, LastMessage: &Message{ID: "m14_7", SenderID: "u6", Text: "The migration dry run finished cleanly.", Timestamp: "Thu", Status: "read"}, UnreadCount: 0, IsGroup: true, Name: ptr("Platform Migration"), Avatar: ptr("https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=200&auto=format&fit=crop"), IsArchived: false, IsCommunity: true},
	{ID: "c15", Participants: []User{currentUser, mockUsers[4], mockUsers[7], mockUsers[10], mockUsers[11]}, LastMessage: &Message{ID: "m15_8", SenderID: "u11", Text: "Let's pin the final itinerary in the announcement thread.", Timestamp: "Thu", Status: "read"}, UnreadCount: 5, IsGroup: true, Name: ptr("Travel Crew"), Avatar: ptr("https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=200&auto=format&fit=crop"), IsArchived: false, IsCommunity: true},
}

// --- Mock Messages ---

var mockMessages = map[string][]Message{
	"c1": {
		{ID: "m1_1", SenderID: "u1", Text: "Morning. Are we still reviewing the latest shell today?", Timestamp: "10:12 AM", Status: "read"},
		{ID: "m1_2", SenderID: "me", Text: "Yep. I cleaned up the sidebar states last night.", Timestamp: "10:14 AM", Status: "read"},
		{ID: "m1_3", SenderID: "u1", Text: "Nice. Did you keep the densities close to WhatsApp Web?", Timestamp: "10:16 AM", Status: "read"},
		{ID: "m1_4", SenderID: "me", Text: "Mostly. The title bar is custom now, but the body is still pretty faithful.", Timestamp: "10:18 AM", Status: "read"},
		{ID: "m1_5", SenderID: "u1", Text: "Good call. Native title bars always looked off in Linux screenshots.", Timestamp: "10:21 AM", Status: "read"},
		{ID: "m1_6", SenderID: "me", Text: "I also added mock API plumbing so the UI doesn't import constants directly anymore.", Timestamp: "10:31 AM", Status: "read"},
		{ID: "m1_7", SenderID: "u1", Text: "Perfect. That'll make swapping the connector in later much less painful.", Timestamp: "10:40 AM", Status: "read"},
		{ID: "m1_8", SenderID: "u1", Text: "Did you see the new architectural sketches?", Timestamp: "10:45 AM", Status: "read"},
	},
	"c2": {
		{ID: "m2_1", SenderID: "u2", Text: "Sent over the latest audit notes.", Timestamp: "Yesterday", Status: "read"},
		{ID: "m2_2", SenderID: "me", Text: "Reading now.", Timestamp: "Yesterday", Status: "read"},
		{ID: "m2_3", SenderID: "u2", Text: "Main issue is still around how we isolate risky features from the safer UX layer.", Timestamp: "Yesterday", Status: "read"},
		{ID: "m2_4", SenderID: "me", Text: "Yeah, I don't want scheduling or receipt suppression touching the normal app state code paths.", Timestamp: "Yesterday", Status: "read"},
		{ID: "m2_5", SenderID: "u2", Text: "Exactly. Keep them behind clear backend capabilities.", Timestamp: "Yesterday", Status: "read"},
		{ID: "m2_6", SenderID: "u2", Text: "Also the shell already feels less like an AI dashboard now.", Timestamp: "Yesterday", Status: "read"},
		{ID: "m2_7", SenderID: "me", Text: "The Precision Architect philosophy looks great.", Timestamp: "Yesterday", Status: "read"},
	},
	"c3": {
		{ID: "m3_1", SenderID: "u3", Text: "Morning all, please check the revised asset list.", Timestamp: "9:02 AM", Status: "read"},
		{ID: "m3_2", SenderID: "u4", Text: "I updated the hero treatments and exported the wide crops.", Timestamp: "9:04 AM", Status: "read"},
		{ID: "m3_3", SenderID: "me", Text: "Need one set optimized for the sidebar preview too.", Timestamp: "9:10 AM", Status: "read"},
		{ID: "m3_4", SenderID: "u6", Text: "Should I produce AVIF and PNG both?", Timestamp: "9:15 AM", Status: "read"},
		{ID: "m3_5", SenderID: "u3", Text: "Yes. PNG for mock fidelity, AVIF for perf testing.", Timestamp: "9:16 AM", Status: "read"},
		{ID: "m3_6", SenderID: "me", Text: "And let's keep the rail icons neutral until the real feature set settles.", Timestamp: "9:22 AM", Status: "read"},
		{ID: "m3_7", SenderID: "u4", Text: "Works for me. Also, communities view should probably feel more like grouped inboxes than giant cards.", Timestamp: "9:30 AM", Status: "read"},
		{ID: "m3_8", SenderID: "u3", Text: "Agreed.", Timestamp: "9:31 AM", Status: "read"},
		{ID: "m3_9", SenderID: "u4", Text: "Sarah: Send over those final PNGs please!", Timestamp: "Yesterday", Status: "read"},
	},
	"c4": {
		{ID: "m4_1", SenderID: "u4", Text: "Need your thoughts on the desktop notification layout.", Timestamp: "Wednesday", Status: "read"},
		{ID: "m4_2", SenderID: "me", Text: "Probably keep it compact. Linux users hate noisy overlays.", Timestamp: "Wednesday", Status: "read"},
		{ID: "m4_3", SenderID: "u4", Text: "True.", Timestamp: "Wednesday", Status: "read"},
		{ID: "m4_4", SenderID: "u4", Text: "Do we want per-group sound and ping behavior in v1?", Timestamp: "Wednesday", Status: "read"},
		{ID: "m4_5", SenderID: "me", Text: "UI hooks now, backend enforcement later.", Timestamp: "Wednesday", Status: "read"},
		{ID: "m4_6", SenderID: "u4", Text: "Call me when you're free.", Timestamp: "Wednesday", Status: "sent"},
	},
	"c5": {
		{ID: "m5_1", SenderID: "u3", Text: "Hi, I've just moved the project assets to the secure server.", Timestamp: "10:45 AM", Status: "read"},
		{ID: "m5_2", SenderID: "me", Text: "Perfect, thanks Sarah. I'll go ahead and archive this thread now to keep the main view clean.", Timestamp: "10:47 AM", Status: "read"},
		{ID: "m5_3", SenderID: "u3", Text: "Makes sense.", Timestamp: "10:48 AM", Status: "read"},
		{ID: "m5_4", SenderID: "me", Text: "We should still surface it in search and exports though.", Timestamp: "10:49 AM", Status: "read"},
		{ID: "m5_5", SenderID: "u3", Text: "The contract has been archived safely.", Timestamp: "10:50 AM", Status: "read"},
	},
	"c6": {
		{ID: "m6_1", SenderID: "u5", Text: "I reworked the login copy so it feels closer to the real product.", Timestamp: "8:40 AM", Status: "read"},
		{ID: "m6_2", SenderID: "me", Text: "Nice. Keep the structure familiar but don't overfit the exact wording.", Timestamp: "8:43 AM", Status: "read"},
		{ID: "m6_3", SenderID: "u5", Text: "Yep. I also want the Keep me signed in control to feel less web-formy.", Timestamp: "8:46 AM", Status: "read"},
		{ID: "m6_4", SenderID: "me", Text: "Agreed. It's a desktop app now, so tone can shift slightly.", Timestamp: "8:52 AM", Status: "read"},
		{ID: "m6_5", SenderID: "u5", Text: "Should I add a secondary state for pairing code later?", Timestamp: "8:57 AM", Status: "read"},
		{ID: "m6_6", SenderID: "me", Text: "Yes, but after QR flow looks solid.", Timestamp: "9:01 AM", Status: "read"},
		{ID: "m6_7", SenderID: "u5", Text: "Typing out the launch copy now. Want first pass in 20?", Timestamp: "9:18 AM", Status: "delivered"},
	},
	"c7": {
		{ID: "m7_1", SenderID: "u6", Text: "Synced the inventory names to the new schema.", Timestamp: "7:22 AM", Status: "read"},
		{ID: "m7_2", SenderID: "me", Text: "Any weird edge cases?", Timestamp: "7:25 AM", Status: "read"},
		{ID: "m7_3", SenderID: "u6", Text: "Only archived chats with stale timestamps.", Timestamp: "7:26 AM", Status: "read"},
		{ID: "m7_4", SenderID: "me", Text: "I'll normalize those before the connector starts writing real data.", Timestamp: "7:31 AM", Status: "read"},
		{ID: "m7_5", SenderID: "u6", Text: "Cool.", Timestamp: "7:33 AM", Status: "read"},
		{ID: "m7_6", SenderID: "me", Text: "Shipping manifests are all reconciled.", Timestamp: "8:07 AM", Status: "read"},
	},
	"c8": {
		{ID: "m8_1", SenderID: "u11", Text: "Venue shortlist is down to 3.", Timestamp: "7:05 AM", Status: "read"},
		{ID: "m8_2", SenderID: "u7", Text: "Can everyone vote before lunch?", Timestamp: "7:11 AM", Status: "read"},
		{ID: "m8_3", SenderID: "me", Text: "I prefer the riverfront option if wifi is stable.", Timestamp: "7:17 AM", Status: "read"},
		{ID: "m8_4", SenderID: "u9", Text: "That one has the nicest breakout rooms too.", Timestamp: "7:21 AM", Status: "read"},
		{ID: "m8_5", SenderID: "u11", Text: "Budget is slightly higher though.", Timestamp: "7:29 AM", Status: "read"},
		{ID: "m8_6", SenderID: "u7", Text: "Still within the ceiling if travel comes in lower.", Timestamp: "7:40 AM", Status: "read"},
		{ID: "m8_7", SenderID: "u9", Text: "I'll call them about projector rentals.", Timestamp: "7:49 AM", Status: "read"},
		{ID: "m8_8", SenderID: "u7", Text: "We should lock the venue by tonight.", Timestamp: "7:55 AM", Status: "read"},
	},
	"c9": {
		{ID: "m9_1", SenderID: "u8", Text: "I've got 160 raws from the station shoot.", Timestamp: "Mon", Status: "read"},
		{ID: "m9_2", SenderID: "me", Text: "Any good verticals for the chat list avatars?", Timestamp: "Mon", Status: "read"},
		{ID: "m9_3", SenderID: "u8", Text: "A few. Sending picks in a minute.", Timestamp: "Mon", Status: "read"},
		{ID: "m9_4", SenderID: "me", Text: "Great.", Timestamp: "Mon", Status: "read"},
		{ID: "m9_5", SenderID: "u8", Text: "Dropped the raw images in the shared drive.", Timestamp: "Mon", Status: "read"},
	},
	"c10": {
		{ID: "m10_1", SenderID: "u9", Text: "Woke up thinking about the empty state copy.", Timestamp: "Sun", Status: "read"},
		{ID: "m10_2", SenderID: "me", Text: "That's either dedication or a problem.", Timestamp: "Sun", Status: "read"},
		{ID: "m10_3", SenderID: "u9", Text: "Probably both.", Timestamp: "Sun", Status: "read"},
		{ID: "m10_4", SenderID: "u9", Text: "Anyway I translated the helper text for French and German mocks.", Timestamp: "Sun", Status: "read"},
		{ID: "m10_5", SenderID: "u9", Text: "Can you review the French copy when you wake up?", Timestamp: "Sun", Status: "delivered"},
	},
	"c11": {
		{ID: "m11_1", SenderID: "u10", Text: "Budget doc is open again.", Timestamp: "Sun", Status: "read"},
		{ID: "m11_2", SenderID: "u12", Text: "Updated line items for flights and hotel holds.", Timestamp: "Sun", Status: "read"},
		{ID: "m11_3", SenderID: "u5", Text: "We should mark provisional numbers visually.", Timestamp: "Sun", Status: "read"},
		{ID: "m11_4", SenderID: "me", Text: "Could do that in the export manager later too.", Timestamp: "Sun", Status: "read"},
		{ID: "m11_5", SenderID: "u7", Text: "Would love filters by confidence level honestly.", Timestamp: "Sun", Status: "read"},
		{ID: "m11_6", SenderID: "u10", Text: "Let's survive v1 first.", Timestamp: "Sun", Status: "read"},
		{ID: "m11_7", SenderID: "me", Text: "Correct answer.", Timestamp: "Sun", Status: "read"},
		{ID: "m11_8", SenderID: "u12", Text: "Still, the grouped notifications are going to be huge for this app.", Timestamp: "Sun", Status: "read"},
		{ID: "m11_9", SenderID: "u10", Text: "Budget sheet updated with the final hotel numbers.", Timestamp: "Sun", Status: "read"},
	},
	"c12": {
		{ID: "m12_1", SenderID: "u11", Text: "How close are we keeping the message spacing to the original?", Timestamp: "Sat", Status: "read"},
		{ID: "m12_2", SenderID: "me", Text: "Very close for now. We'll diverge later when bulk actions land.", Timestamp: "Sat", Status: "read"},
		{ID: "m12_3", SenderID: "u11", Text: "Makes sense.", Timestamp: "Sat", Status: "read"},
		{ID: "m12_4", SenderID: "me", Text: "I'll send a cleaner build after lunch.", Timestamp: "Sat", Status: "read"},
	},
	"c13": {
		{ID: "m13_1", SenderID: "u12", Text: "Finance asked for the original invoice thread.", Timestamp: "Fri", Status: "read"},
		{ID: "m13_2", SenderID: "me", Text: "It's in exports, but I can resend the PDFs too.", Timestamp: "Fri", Status: "read"},
		{ID: "m13_3", SenderID: "u12", Text: "Only if they ask.", Timestamp: "Fri", Status: "read"},
		{ID: "m13_4", SenderID: "me", Text: "Okay.", Timestamp: "Fri", Status: "read"},
		{ID: "m13_5", SenderID: "u12", Text: "I'll keep this thread archived after that.", Timestamp: "Fri", Status: "read"},
		{ID: "m13_6", SenderID: "u12", Text: "Archive this one after finance replies.", Timestamp: "Fri", Status: "read"},
	},
	"c14": {
		{ID: "m14_1", SenderID: "u2", Text: "Dry run starts at 6 PM UTC.", Timestamp: "Thu", Status: "read"},
		{ID: "m14_2", SenderID: "u6", Text: "I'll monitor the connector logs.", Timestamp: "Thu", Status: "read"},
		{ID: "m14_3", SenderID: "u10", Text: "Make sure the mock transport and the eventual transport share the same shape.", Timestamp: "Thu", Status: "read"},
		{ID: "m14_4", SenderID: "me", Text: "Already doing that with the mock API boundary.", Timestamp: "Thu", Status: "read"},
		{ID: "m14_5", SenderID: "u2", Text: "Good.", Timestamp: "Thu", Status: "read"},
		{ID: "m14_6", SenderID: "u6", Text: "No schema drift so far.", Timestamp: "Thu", Status: "read"},
		{ID: "m14_7", SenderID: "u6", Text: "The migration dry run finished cleanly.", Timestamp: "Thu", Status: "read"},
	},
	"c15": {
		{ID: "m15_1", SenderID: "u5", Text: "Who's booking airport transfers?", Timestamp: "Thu", Status: "read"},
		{ID: "m15_2", SenderID: "u8", Text: "I can take pickups if someone else handles hotel check-in.", Timestamp: "Thu", Status: "read"},
		{ID: "m15_3", SenderID: "u11", Text: "Happy to do hotel.", Timestamp: "Thu", Status: "read"},
		{ID: "m15_4", SenderID: "me", Text: "Please pin the final timing once settled.", Timestamp: "Thu", Status: "read"},
		{ID: "m15_5", SenderID: "u12", Text: "Need dietary list too.", Timestamp: "Thu", Status: "read"},
		{ID: "m15_6", SenderID: "u5", Text: "I'll gather that in a sheet.", Timestamp: "Thu", Status: "read"},
		{ID: "m15_7", SenderID: "u8", Text: "Flight arrival spread is wider than I thought.", Timestamp: "Thu", Status: "read"},
		{ID: "m15_8", SenderID: "u11", Text: "Let's pin the final itinerary in the announcement thread.", Timestamp: "Thu", Status: "read"},
	},
}
