import type { Chat, Message, User } from "./types";

export const CURRENT_USER: User = {
  id: "me",
  name: "Me",
  avatar:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuBQpbQel9oNKt2XyTxpX44jsBlk2knXI5Cc72a-eHNJf9Sl8OCqHOvfH_dT7eTzDYCKG1OOVx9jVomNf0tOmyN26e80wI7-W3IuVhbiYkt23dw8V4wu4rOiqXGAMQI7vOKFMLpjyiSLzeFbGhSueo_vIKsm1wDHRkRHBRecm1qPzAB_2EQT4TgYszEuXJgD8dE6eZUq-8zcCYpYbOcY5nZ0d2R3ytZu4OJNacUzFmE5HdlWeN2uC56XGi7QkO4ASLE0MI2kLRkHfrc",
  status: "online",
};

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Alex Thompson",
    avatar:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCKkuDTlknPZ9zVu10T2BVU1Mkg8bSF67xEr-e0kPZN3xyYMPIYhKsSQZIbXAWcEnPuV-q5JuNqP75mgnzzo6adhVebJFglRX7tsYtuAkNt-iBKA6Wug0UQFd7GfCxUpWTT2dJ5OQkzGL15olsiwxQakgfeN_wG2Aca2yJjvG4myL5ve7nXyTuTX8WekJTM5ZPnkamaL19X_cNkuIo2JzZwjdhjSZcl_egG-XQDVOVJmtOJT1c0l66DnZNjdHOcM7vPfTsZkW_yVPQ",
    status: "online",
  },
  {
    id: "u2",
    name: "David Chen",
    avatar:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAcDAkeKd_OgauMWIlHdnx-AScpLSyGGcMnPrajrzneShk5iCGnl1SfnxTlQzXgnMKKp-hdTE8ILHacIW594dvVC0Azyt6ANx_Z88ygRDxmGwB3ZbOVFLoS08q9vTTrQRTAXsTES20IeYstJdLKBW54R-PQ3tzmIgmQR_ay4ZY9IASKOBGCnpfWiszxzWJTMWd9wKPRAIItJJJNfDoPCfJ0uzU5E3O1hHFSbsJlJgRkRQzYeL9W5Y7FmYLUh25X-1bSkbk8EpqrWDk",
    status: "last seen yesterday",
  },
  {
    id: "u3",
    name: "Sarah Jenkins",
    avatar:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB3WzGGXuON5bdmZa6KZ5Y0L3WMvtDN3AAQoYAbGHj1H5NvlymI3Q2vdpqdd_bGgOHAmpXtqd2ayDd7JTvMnKkqNOB7Bbm_YjraiYzeRJQJ6F-Gp4ZYew6FW6dkgE6J8yGvpVMNkbKHisADs9W8LOsyZRPqsoQAYlfmkOc6j3Rg79WG-3rg9x72yFSF9EC6es2aUF9zyMbFmajpVJiTgVD5zzgQ23TRfx93WL4_J6rsICEdUq0wMGKUEafip4JLExzV3_190zcz7kI",
    status: "last seen 2 hours ago",
  },
  {
    id: "u4",
    name: "Maria Rodriguez",
    avatar:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuD0odOdWjMhHLpR8RskLpq1kLtf12AqJssSW8hUvkiNhl4S3xYveXeXR4dlRDDLqW5brU3grf1Mjuzvr0x7W3FHhF-OjUpdp2u85T1mZCyF60I1PfpdzsvcxVXq76jchUhQNgOgnmMmrgD0HKBwbYpZIAK3WVdEbAm10pf_INEZiVzF_QBqGzwOrqUGyB7lCZ4OfYcHi2WrDLsUzM-3wFMSUSxJTJ83faaUSLZsrzJeszvHm-xzqFCiIjvphNDXLU5SLA9dReCMfgA",
    status: "online",
  },
  {
    id: "u5",
    name: "Priya Nair",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop",
    status: "typing...",
  },
  {
    id: "u6",
    name: "Omar Haddad",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop",
    status: "online",
  },
  {
    id: "u7",
    name: "Nina Park",
    avatar: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?q=80&w=200&auto=format&fit=crop",
    status: "last seen today at 9:02 AM",
  },
  {
    id: "u8",
    name: "Leo Martins",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=200&auto=format&fit=crop",
    status: "online",
  },
  {
    id: "u9",
    name: "Jules Bernard",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop",
    status: "last seen monday",
  },
  {
    id: "u10",
    name: "Marta Kowalski",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=200&auto=format&fit=crop",
    status: "online",
  },
  {
    id: "u11",
    name: "Noah Williams",
    avatar: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?q=80&w=200&auto=format&fit=crop",
    status: "online",
  },
  {
    id: "u12",
    name: "Elena Petrova",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop",
    status: "last seen today at 8:11 AM",
  },
];

export const MOCK_CHATS: Chat[] = [
  {
    id: "c1",
    participants: [CURRENT_USER, MOCK_USERS[0]],
    lastMessage: {
      id: "m1_8",
      senderId: "u1",
      text: "Did you see the new architectural sketches?",
      timestamp: "10:45 AM",
      status: "read",
    },
    unreadCount: 2,
    isGroup: false,
    isArchived: false,
    isStarred: true,
  },
  {
    id: "c2",
    participants: [CURRENT_USER, MOCK_USERS[1]],
    lastMessage: {
      id: "m2_7",
      senderId: "me",
      text: "The Precision Architect philosophy looks great.",
      timestamp: "Yesterday",
      status: "read",
    },
    unreadCount: 0,
    isGroup: false,
    isArchived: false,
    isStarred: true,
  },
  {
    id: "c3",
    participants: [CURRENT_USER, MOCK_USERS[0], MOCK_USERS[2], MOCK_USERS[3], MOCK_USERS[5]],
    lastMessage: {
      id: "m3_9",
      senderId: "u4",
      text: "Sarah: Send over those final PNGs please!",
      timestamp: "Yesterday",
      status: "read",
    },
    unreadCount: 0,
    isGroup: true,
    name: "Design Sprint 2024",
    avatar: "https://images.unsplash.com/photo-1522071823991-b96767a1c56f?q=80&w=200&auto=format&fit=crop",
    isArchived: false,
    isStarred: true,
    isCommunity: true,
  },
  {
    id: "c4",
    participants: [CURRENT_USER, MOCK_USERS[3]],
    lastMessage: {
      id: "m4_6",
      senderId: "u4",
      text: "Call me when you're free.",
      timestamp: "Wednesday",
      status: "sent",
    },
    unreadCount: 0,
    isGroup: false,
    isArchived: false,
  },
  {
    id: "c5",
    participants: [CURRENT_USER, MOCK_USERS[2]],
    lastMessage: {
      id: "m5_5",
      senderId: "u3",
      text: "The contract has been archived safely.",
      timestamp: "Dec 22",
      status: "read",
    },
    unreadCount: 0,
    isGroup: false,
    isArchived: true,
  },
  {
    id: "c6",
    participants: [CURRENT_USER, MOCK_USERS[4]],
    lastMessage: {
      id: "m6_7",
      senderId: "u5",
      text: "Typing out the launch copy now. Want first pass in 20?",
      timestamp: "9:18 AM",
      status: "delivered",
    },
    unreadCount: 4,
    isGroup: false,
    isArchived: false,
    isStarred: true,
  },
  {
    id: "c7",
    participants: [CURRENT_USER, MOCK_USERS[5]],
    lastMessage: {
      id: "m7_6",
      senderId: "me",
      text: "Shipping manifests are all reconciled.",
      timestamp: "8:07 AM",
      status: "read",
    },
    unreadCount: 0,
    isGroup: false,
    isArchived: false,
  },
  {
    id: "c8",
    participants: [CURRENT_USER, MOCK_USERS[6], MOCK_USERS[8], MOCK_USERS[10]],
    lastMessage: {
      id: "m8_8",
      senderId: "u7",
      text: "We should lock the venue by tonight.",
      timestamp: "7:55 AM",
      status: "read",
    },
    unreadCount: 7,
    isGroup: true,
    name: "Offsite Planning",
    avatar: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=200&auto=format&fit=crop",
    isArchived: false,
    isCommunity: true,
  },
  {
    id: "c9",
    participants: [CURRENT_USER, MOCK_USERS[7]],
    lastMessage: {
      id: "m9_5",
      senderId: "u8",
      text: "Dropped the raw images in the shared drive.",
      timestamp: "Mon",
      status: "read",
    },
    unreadCount: 0,
    isGroup: false,
    isArchived: false,
  },
  {
    id: "c10",
    participants: [CURRENT_USER, MOCK_USERS[8]],
    lastMessage: {
      id: "m10_5",
      senderId: "u9",
      text: "Can you review the French copy when you wake up?",
      timestamp: "Sun",
      status: "delivered",
    },
    unreadCount: 1,
    isGroup: false,
    isArchived: false,
  },
  {
    id: "c11",
    participants: [CURRENT_USER, MOCK_USERS[9], MOCK_USERS[11], MOCK_USERS[4], MOCK_USERS[6]],
    lastMessage: {
      id: "m11_9",
      senderId: "u10",
      text: "Budget sheet updated with the final hotel numbers.",
      timestamp: "Sun",
      status: "read",
    },
    unreadCount: 3,
    isGroup: true,
    name: "Ops Core",
    avatar: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=200&auto=format&fit=crop",
    isArchived: false,
    isCommunity: true,
    isStarred: true,
  },
  {
    id: "c12",
    participants: [CURRENT_USER, MOCK_USERS[10]],
    lastMessage: {
      id: "m12_4",
      senderId: "me",
      text: "I'll send a cleaner build after lunch.",
      timestamp: "Sat",
      status: "read",
    },
    unreadCount: 0,
    isGroup: false,
    isArchived: false,
  },
  {
    id: "c13",
    participants: [CURRENT_USER, MOCK_USERS[11]],
    lastMessage: {
      id: "m13_6",
      senderId: "u12",
      text: "Archive this one after finance replies.",
      timestamp: "Fri",
      status: "read",
    },
    unreadCount: 0,
    isGroup: false,
    isArchived: true,
  },
  {
    id: "c14",
    participants: [CURRENT_USER, MOCK_USERS[1], MOCK_USERS[5], MOCK_USERS[9]],
    lastMessage: {
      id: "m14_7",
      senderId: "u6",
      text: "The migration dry run finished cleanly.",
      timestamp: "Thu",
      status: "read",
    },
    unreadCount: 0,
    isGroup: true,
    name: "Platform Migration",
    avatar: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=200&auto=format&fit=crop",
    isArchived: false,
    isCommunity: true,
  },
  {
    id: "c15",
    participants: [CURRENT_USER, MOCK_USERS[4], MOCK_USERS[7], MOCK_USERS[10], MOCK_USERS[11]],
    lastMessage: {
      id: "m15_8",
      senderId: "u11",
      text: "Let's pin the final itinerary in the announcement thread.",
      timestamp: "Thu",
      status: "read",
    },
    unreadCount: 5,
    isGroup: true,
    name: "Travel Crew",
    avatar: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=200&auto=format&fit=crop",
    isArchived: false,
    isCommunity: true,
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  c1: [
    { id: "m1_1", senderId: "u1", text: "Morning. Are we still reviewing the latest shell today?", timestamp: "10:12 AM", status: "read" },
    { id: "m1_2", senderId: "me", text: "Yep. I cleaned up the sidebar states last night.", timestamp: "10:14 AM", status: "read" },
    { id: "m1_3", senderId: "u1", text: "Nice. Did you keep the densities close to WhatsApp Web?", timestamp: "10:16 AM", status: "read" },
    { id: "m1_4", senderId: "me", text: "Mostly. The title bar is custom now, but the body is still pretty faithful.", timestamp: "10:18 AM", status: "read" },
    { id: "m1_5", senderId: "u1", text: "Good call. Native title bars always looked off in Linux screenshots.", timestamp: "10:21 AM", status: "read" },
    { id: "m1_6", senderId: "me", text: "I also added mock API plumbing so the UI doesn't import constants directly anymore.", timestamp: "10:31 AM", status: "read" },
    { id: "m1_7", senderId: "u1", text: "Perfect. That'll make swapping the connector in later much less painful.", timestamp: "10:40 AM", status: "read" },
    { id: "m1_8", senderId: "u1", text: "Did you see the new architectural sketches?", timestamp: "10:45 AM", status: "read" },
  ],
  c2: [
    { id: "m2_1", senderId: "u2", text: "Sent over the latest audit notes.", timestamp: "Yesterday", status: "read" },
    { id: "m2_2", senderId: "me", text: "Reading now.", timestamp: "Yesterday", status: "read" },
    { id: "m2_3", senderId: "u2", text: "Main issue is still around how we isolate risky features from the safer UX layer.", timestamp: "Yesterday", status: "read" },
    { id: "m2_4", senderId: "me", text: "Yeah, I don't want scheduling or receipt suppression touching the normal app state code paths.", timestamp: "Yesterday", status: "read" },
    { id: "m2_5", senderId: "u2", text: "Exactly. Keep them behind clear backend capabilities.", timestamp: "Yesterday", status: "read" },
    { id: "m2_6", senderId: "u2", text: "Also the shell already feels less like an AI dashboard now.", timestamp: "Yesterday", status: "read" },
    { id: "m2_7", senderId: "me", text: "The Precision Architect philosophy looks great.", timestamp: "Yesterday", status: "read" },
  ],
  c3: [
    { id: "m3_1", senderId: "u3", text: "Morning all, please check the revised asset list.", timestamp: "9:02 AM", status: "read" },
    { id: "m3_2", senderId: "u4", text: "I updated the hero treatments and exported the wide crops.", timestamp: "9:04 AM", status: "read" },
    { id: "m3_3", senderId: "me", text: "Need one set optimized for the sidebar preview too.", timestamp: "9:10 AM", status: "read" },
    { id: "m3_4", senderId: "u6", text: "Should I produce AVIF and PNG both?", timestamp: "9:15 AM", status: "read" },
    { id: "m3_5", senderId: "u3", text: "Yes. PNG for mock fidelity, AVIF for perf testing.", timestamp: "9:16 AM", status: "read" },
    { id: "m3_6", senderId: "me", text: "And let's keep the rail icons neutral until the real feature set settles.", timestamp: "9:22 AM", status: "read" },
    { id: "m3_7", senderId: "u4", text: "Works for me. Also, communities view should probably feel more like grouped inboxes than giant cards.", timestamp: "9:30 AM", status: "read" },
    { id: "m3_8", senderId: "u3", text: "Agreed.", timestamp: "9:31 AM", status: "read" },
    { id: "m3_9", senderId: "u4", text: "Sarah: Send over those final PNGs please!", timestamp: "Yesterday", status: "read" },
  ],
  c4: [
    { id: "m4_1", senderId: "u4", text: "Need your thoughts on the desktop notification layout.", timestamp: "Wednesday", status: "read" },
    { id: "m4_2", senderId: "me", text: "Probably keep it compact. Linux users hate noisy overlays.", timestamp: "Wednesday", status: "read" },
    { id: "m4_3", senderId: "u4", text: "True.", timestamp: "Wednesday", status: "read" },
    { id: "m4_4", senderId: "u4", text: "Do we want per-group sound and ping behavior in v1?", timestamp: "Wednesday", status: "read" },
    { id: "m4_5", senderId: "me", text: "UI hooks now, backend enforcement later.", timestamp: "Wednesday", status: "read" },
    { id: "m4_6", senderId: "u4", text: "Call me when you're free.", timestamp: "Wednesday", status: "sent" },
  ],
  c5: [
    { id: "m5_1", senderId: "u3", text: "Hi, I've just moved the project assets to the secure server.", timestamp: "10:45 AM", status: "read" },
    { id: "m5_2", senderId: "me", text: "Perfect, thanks Sarah. I'll go ahead and archive this thread now to keep the main view clean.", timestamp: "10:47 AM", status: "read" },
    { id: "m5_3", senderId: "u3", text: "Makes sense.", timestamp: "10:48 AM", status: "read" },
    { id: "m5_4", senderId: "me", text: "We should still surface it in search and exports though.", timestamp: "10:49 AM", status: "read" },
    { id: "m5_5", senderId: "u3", text: "The contract has been archived safely.", timestamp: "10:50 AM", status: "read" },
  ],
  c6: [
    { id: "m6_1", senderId: "u5", text: "I reworked the login copy so it feels closer to the real product.", timestamp: "8:40 AM", status: "read" },
    { id: "m6_2", senderId: "me", text: "Nice. Keep the structure familiar but don't overfit the exact wording.", timestamp: "8:43 AM", status: "read" },
    { id: "m6_3", senderId: "u5", text: "Yep. I also want the Keep me signed in control to feel less web-formy.", timestamp: "8:46 AM", status: "read" },
    { id: "m6_4", senderId: "me", text: "Agreed. It's a desktop app now, so tone can shift slightly.", timestamp: "8:52 AM", status: "read" },
    { id: "m6_5", senderId: "u5", text: "Should I add a secondary state for pairing code later?", timestamp: "8:57 AM", status: "read" },
    { id: "m6_6", senderId: "me", text: "Yes, but after QR flow looks solid.", timestamp: "9:01 AM", status: "read" },
    { id: "m6_7", senderId: "u5", text: "Typing out the launch copy now. Want first pass in 20?", timestamp: "9:18 AM", status: "delivered" },
  ],
  c7: [
    { id: "m7_1", senderId: "u6", text: "Synced the inventory names to the new schema.", timestamp: "7:22 AM", status: "read" },
    { id: "m7_2", senderId: "me", text: "Any weird edge cases?", timestamp: "7:25 AM", status: "read" },
    { id: "m7_3", senderId: "u6", text: "Only archived chats with stale timestamps.", timestamp: "7:26 AM", status: "read" },
    { id: "m7_4", senderId: "me", text: "I'll normalize those before the connector starts writing real data.", timestamp: "7:31 AM", status: "read" },
    { id: "m7_5", senderId: "u6", text: "Cool.", timestamp: "7:33 AM", status: "read" },
    { id: "m7_6", senderId: "me", text: "Shipping manifests are all reconciled.", timestamp: "8:07 AM", status: "read" },
  ],
  c8: [
    { id: "m8_1", senderId: "u11", text: "Venue shortlist is down to 3.", timestamp: "7:05 AM", status: "read" },
    { id: "m8_2", senderId: "u7", text: "Can everyone vote before lunch?", timestamp: "7:11 AM", status: "read" },
    { id: "m8_3", senderId: "me", text: "I prefer the riverfront option if wifi is stable.", timestamp: "7:17 AM", status: "read" },
    { id: "m8_4", senderId: "u9", text: "That one has the nicest breakout rooms too.", timestamp: "7:21 AM", status: "read" },
    { id: "m8_5", senderId: "u11", text: "Budget is slightly higher though.", timestamp: "7:29 AM", status: "read" },
    { id: "m8_6", senderId: "u7", text: "Still within the ceiling if travel comes in lower.", timestamp: "7:40 AM", status: "read" },
    { id: "m8_7", senderId: "u9", text: "I'll call them about projector rentals.", timestamp: "7:49 AM", status: "read" },
    { id: "m8_8", senderId: "u7", text: "We should lock the venue by tonight.", timestamp: "7:55 AM", status: "read" },
  ],
  c9: [
    { id: "m9_1", senderId: "u8", text: "I've got 160 raws from the station shoot.", timestamp: "Mon", status: "read" },
    { id: "m9_2", senderId: "me", text: "Any good verticals for the chat list avatars?", timestamp: "Mon", status: "read" },
    { id: "m9_3", senderId: "u8", text: "A few. Sending picks in a minute.", timestamp: "Mon", status: "read" },
    { id: "m9_4", senderId: "me", text: "Great.", timestamp: "Mon", status: "read" },
    { id: "m9_5", senderId: "u8", text: "Dropped the raw images in the shared drive.", timestamp: "Mon", status: "read" },
  ],
  c10: [
    { id: "m10_1", senderId: "u9", text: "Woke up thinking about the empty state copy.", timestamp: "Sun", status: "read" },
    { id: "m10_2", senderId: "me", text: "That's either dedication or a problem.", timestamp: "Sun", status: "read" },
    { id: "m10_3", senderId: "u9", text: "Probably both.", timestamp: "Sun", status: "read" },
    { id: "m10_4", senderId: "u9", text: "Anyway I translated the helper text for French and German mocks.", timestamp: "Sun", status: "read" },
    { id: "m10_5", senderId: "u9", text: "Can you review the French copy when you wake up?", timestamp: "Sun", status: "delivered" },
  ],
  c11: [
    { id: "m11_1", senderId: "u10", text: "Budget doc is open again.", timestamp: "Sun", status: "read" },
    { id: "m11_2", senderId: "u12", text: "Updated line items for flights and hotel holds.", timestamp: "Sun", status: "read" },
    { id: "m11_3", senderId: "u5", text: "We should mark provisional numbers visually.", timestamp: "Sun", status: "read" },
    { id: "m11_4", senderId: "me", text: "Could do that in the export manager later too.", timestamp: "Sun", status: "read" },
    { id: "m11_5", senderId: "u7", text: "Would love filters by confidence level honestly.", timestamp: "Sun", status: "read" },
    { id: "m11_6", senderId: "u10", text: "Let's survive v1 first.", timestamp: "Sun", status: "read" },
    { id: "m11_7", senderId: "me", text: "Correct answer.", timestamp: "Sun", status: "read" },
    { id: "m11_8", senderId: "u12", text: "Still, the grouped notifications are going to be huge for this app.", timestamp: "Sun", status: "read" },
    { id: "m11_9", senderId: "u10", text: "Budget sheet updated with the final hotel numbers.", timestamp: "Sun", status: "read" },
  ],
  c12: [
    { id: "m12_1", senderId: "u11", text: "How close are we keeping the message spacing to the original?", timestamp: "Sat", status: "read" },
    { id: "m12_2", senderId: "me", text: "Very close for now. We'll diverge later when bulk actions land.", timestamp: "Sat", status: "read" },
    { id: "m12_3", senderId: "u11", text: "Makes sense.", timestamp: "Sat", status: "read" },
    { id: "m12_4", senderId: "me", text: "I'll send a cleaner build after lunch.", timestamp: "Sat", status: "read" },
  ],
  c13: [
    { id: "m13_1", senderId: "u12", text: "Finance asked for the original invoice thread.", timestamp: "Fri", status: "read" },
    { id: "m13_2", senderId: "me", text: "It's in exports, but I can resend the PDFs too.", timestamp: "Fri", status: "read" },
    { id: "m13_3", senderId: "u12", text: "Only if they ask.", timestamp: "Fri", status: "read" },
    { id: "m13_4", senderId: "me", text: "Okay.", timestamp: "Fri", status: "read" },
    { id: "m13_5", senderId: "u12", text: "I'll keep this thread archived after that.", timestamp: "Fri", status: "read" },
    { id: "m13_6", senderId: "u12", text: "Archive this one after finance replies.", timestamp: "Fri", status: "read" },
  ],
  c14: [
    { id: "m14_1", senderId: "u2", text: "Dry run starts at 6 PM UTC.", timestamp: "Thu", status: "read" },
    { id: "m14_2", senderId: "u6", text: "I'll monitor the connector logs.", timestamp: "Thu", status: "read" },
    { id: "m14_3", senderId: "u10", text: "Make sure the mock transport and the eventual transport share the same shape.", timestamp: "Thu", status: "read" },
    { id: "m14_4", senderId: "me", text: "Already doing that with the mock API boundary.", timestamp: "Thu", status: "read" },
    { id: "m14_5", senderId: "u2", text: "Good.", timestamp: "Thu", status: "read" },
    { id: "m14_6", senderId: "u6", text: "No schema drift so far.", timestamp: "Thu", status: "read" },
    { id: "m14_7", senderId: "u6", text: "The migration dry run finished cleanly.", timestamp: "Thu", status: "read" },
  ],
  c15: [
    { id: "m15_1", senderId: "u5", text: "Who's booking airport transfers?", timestamp: "Thu", status: "read" },
    { id: "m15_2", senderId: "u8", text: "I can take pickups if someone else handles hotel check-in.", timestamp: "Thu", status: "read" },
    { id: "m15_3", senderId: "u11", text: "Happy to do hotel.", timestamp: "Thu", status: "read" },
    { id: "m15_4", senderId: "me", text: "Please pin the final timing once settled.", timestamp: "Thu", status: "read" },
    { id: "m15_5", senderId: "u12", text: "Need dietary list too.", timestamp: "Thu", status: "read" },
    { id: "m15_6", senderId: "u5", text: "I'll gather that in a sheet.", timestamp: "Thu", status: "read" },
    { id: "m15_7", senderId: "u8", text: "Flight arrival spread is wider than I thought.", timestamp: "Thu", status: "read" },
    { id: "m15_8", senderId: "u11", text: "Let's pin the final itinerary in the announcement thread.", timestamp: "Thu", status: "read" },
  ],
};
